lib/cluster.js
The issue came up when connecting to a load balancer, sitting in front of the redis cluster nodes, and attempting to subscribe as soon as the 'ready' event was fired.  The load balancer's IP:port is not in redis cluster's list of nodes so the connection was disconnected and removed, causing the subscribe to be sent to the disconnected node.
=> Resolves a bug with cluster where a subscribe is sent to a disconnected node

lib/cluster.js, lib/redis.js, test/functional/cluster.js
- Cluster slots are now served with both Master and Slave instances.
The purpose is to use the client in a `readonly` mode to scale reads.
Each client individual issues a `readonly` once `ready`.
Each node in the cluster is connected to, maintaining a pool of Master nodes and SlaveNodes.
=> Adds ReadOnly mode for Standalone/Cluster mode

index.js
Add a print function for convenience. The lack of ioredis.print can cause an error if it is used to replace node_redis.
=> Add print function

lib/cluster.js
In Redis Cluster mode, arg3 (message) was not getting passed to pmessage/pmessageBuffer.
=> pmessage now properly returns pattern, channel, message

lib/redis.js
When server uses Unix socket, the debug message of the status changes
still indicated [host:port] even though the connector was using the
socket's path correctly.
=> Fixes status debug message in case of Unix socket path

lib/script.js, test/functional/pipeline.js
Hi!
I just spent the past few hours debugging a problem I had with running a custom lua script in a Pipeline.
Part of the issue is that `Pipeline.prototype.sendCommand(...)` returns `this` (a Pipeline instance for chaining) instead of the command's Promise (which every other sendCommand method seems to return).
```js
// lib/pipeline.js L146
Pipeline.prototype.sendCommand = function (command) {
var position = this._queue.length;
var _this = this;
command.promise.then(function (result) {
_this.fillResult([null, result], position);
}).catch(function (error) {
_this.fillResult([error], position);
});
this._queue.push(command);
// seems every where else returns command.promise
// this is, however, necessary because it's used for chaining
return this;
};
```
When this Pipeline instance filters …
=> Fix not running callback in pipeline custom command

lib/utils/index.js, test/functional/watch-exec.js
When using [WATCH/EXEC](http://redis.io/topics/transactions) transactions in Redis, if the transaction rolls back (due to one of the watched keys being modified), the EXEC command does not return a result (instead of returning an array).
Currently this leads to `utils/wrapMultiResult` failing with a `TypeError: Cannot read property 'length' of null`. 
This PR adds tests for WATCH/EXEC (normal and rollback) and fixes the problem by making `wrapMultiResult` a little more defensive.
=> Handle watch-exec rollback correctly

lib/redis/event_handler.js, test/functional/connection.js
This fixes an issue where we restored the previous state AFTER we ran the offline and previous command queue, which could cause us to miss unsubscribe requests. Unit test added for this scenario.
=> Previous Subscription State Error

lib/cluster.js
The allNodes array was accumulating the nodes for all previously processed entries in the `cluster slots` result. This meant read-only clients sometimes repeatedly targeting an incorrect node, especially in larger clusters.
=> Fix for allNodes array containing nodes not serving the specified slot.

lib/connectors/sentinel_connector.js
This change allows sentinel connections to use the user-specified connection timeout instead of the hard-coded value of 2000 milliseconds. In cases where a `connectTimeout` is not specified, the default value in `Redis.defaultOptions` will be used (currently 3000 millis).
=> Use given `connectTimeout` for sentinel connections

lib/redis.js
When `ioredis` connects to a sentinel, retrieves the host and port of the master server, it stills outputs `localhost:6379` in the debug output, which is usually incorrect/misleading.
Even with debug output disabled, it would be nice to be able to print the address of the connected redis server when the `#ready` event fires, e.g.:
```javascript
redis.on('ready', function () {
console.log('Connected to Redis @ %s:%s', redis.options.host, redis.options.port);
});
```
Now, maybe `options` is not the best place to store this, but since this is what's used for the debug/status messages (e.g. `ioredis:redis status[192.168.33.10:26379]: connecting -> connect +1ms`), I felt this was the simplest place to put it.
=> Update options host & port with resolved Redis server

lib/redis.js, lib/redis/event_handler.js, test/functional/connection.js
From the redis documentation: "setting names to connections is a good way to debug connection leaks due to bugs in the application using Redis.". The problem is on subscribed connection the name must be set before any subscribe, although the developer can take care of it on the initial connection, the name is lost if ioredis reconnects automatically and resubscribe. A new option "connectionName" can be sued to set the name and leave it to ioredis to set the name consistently across reconnections.
=> allow the connection to be named even if susbscribed and reconnected

.travis.yml
Occasionally some tests fail in Travis for no reason, we just use a dirty way to simply retry them.
=> Retry when test fails

lib/cluster.js
this is a critical fix as the timeout never gets nulled so it will not work after a single failover
=> fix critical typo in handleError

lib/cluster.js
If slot was not previously discovered by ioredis - it would cause a crash as it
would try to rewrite a masterNode on a missing object
Should close #231
=> fix: "MOVED" err not crashing process when slot was not assigned

README.md, lib/cluster.js
Provides ability to send arbitrary commands too all nodes in a requested group or
just a handy helper to select nodes from such a group
Supports 'all', 'masters' and 'slaves' groups exposing `call` and `callBuffer` command
semantics similar to Commander
=> feat: revisit of .to(nodeGroup) command

lib/cluster.js
fixes #233 
The problem was that the `_.defaults()` function was using the `options` argument that was passed to it as the base object, and when that object was being freezed by `Object.freeze()`, the defaults weren't being used.
=> fix issue where options were not changed if passed freezed object

README.md, lib/cluster/index.js, test/functional/cluster.js
=> feat(cluster): add the option for a custom node selector in scaleReads

API.md, lib/redis.js
Just adjusting the description of keepAlive option (the way to disable it was in connectionName option)
=> docs: fix the description of keepAlive option

lib/command.js, lib/pipeline.js, test/functional/transaction.js
BREAKING CHANGE:
1. Reply transformers is supported inside transactions.
2. `Pipeline#execBuffer()` is deprecated. Use `Pipeline#exec()` instead.
Closes #158.
=> feat(transaction): transform replies of transactions

lib/cluster/index.js, lib/redis.js, package.json, test/functional/cluster.js, test/functional/lazy_connect.js
Before this change, when disconnecting from a cluster, the nodes will be disconnected one by one. However, when the subscriber is disconnected, a new subscriber will be connected to in `-node` event, leading the cluster keeping connected.
Related issue: #277
=> fix(CLUSTER): fix cluster not disconnected when called disconnect method

README.md, lib/cluster/index.js, lib/redis.js, lib/redis/event_handler.js, test/functional/auth.js, test/functional/ready_check.js
Use a unified error event will be more easier to deal with (Many people forget to listen to the `authError` event).
Note that we should disconnect from the Redis since many other libraries (e.g. connect-redis) suppose `error` event will be followed by a reconnection.
BREAKING CHANGE:
Authentication related errors are emited with "error" event,
instead of "authError" event
=> feat: emit authentication related errors with "error" event

.travis.yml
Release notes: https://nodejs.org/en/blog/release/v6.0.0/
=> feat: add support for Node.js v6

lib/connectors/sentinel_connector.js
Basically same as https://github.com/luin/ioredis/pull/155 , but this time passing the `dropBufferSupport` option also through the sentinel-connector.
Would it be better to just pass the whole `this.options`, and only override or exclude properties like `host`, `port` and `enableReadyCheck`?
=> Use given 'dropBufferSupport' for sentinel connections

examples/basic_operations.js
Existing docs have no examples of CONFIG SET, and no mention of multi-word commands.
=> Add example of changing Redis server config

README.md
Maybe some explicit documentation will help prevent issues like #239 and #254.
=> docs(README): add warning for key prefixing with some commands

API.md, README.md, lib/redis.js, lib/redis/parser.js
The monitor events generated in ioredis don't currently include all of the data that redis provides (The redis database and source are currently missing).
This adds the extra parameters to the end of the emitted event.
~~It seems like my text editor has cleared whitespace from the end of the lines of your docs too, but I can remove those changes if it's preferred to keep the pull request simpler.~~
=> Include missing data in monitor events

lib/pipeline.js, test/functional/drop_buffer_support.js, test/functional/transaction.js
fixes #313 + regression test.
@luin There is another issue now with `dropBufferSupport` regarding transactions that combine both Buffer & non-Buffer methods.
I'm not sure this is supported now and will cause an error.
=> fix transaction with dropBufferSupport:true

lib/command.js
`getKeyPart` methods is not used anymore as the package redis-commands is used. Remove it won't break BC since it's not a public API (not listed on https://github.com/luin/ioredis/blob/master/API.md).
=> refactor: remove unused Command#getKeyPart

lib/cluster/index.js, test/functional/cluster.js
If a master node in the Redis cluster does not have any slots, it is not returned by the `cluster slots` command, and so does not have a client in the connectionPool. If slots are migrated to this new master node, the old master node returns an `ASK` error with the new node details. At the moment ioredis looks up the node in the connectionPool but it doesn't exist, so the following error is returned:
```
TypeError: Cannot call method 'asking' of undefined
at tryConnection (/var/www/document-updater/releases/5543/node_modules/ioredis/lib/cluster/index.js:464:19)
at Object._this.handleError.ask (/var/www/document-updater/releases/5543/node_modules/ioredis/lib/cluster/index.js:404:11)
at Cluster.handleError (/var/www/document-updater/releases/5543/node_modules/ioredis/lib/cluster/index.js:503 …
```
=> Ensure node exists before being redirected via an ASK

lib/cluster/connection_pool.js, lib/cluster/index.js, lib/redis.js, lib/redis/event_handler.js, test/functional/lazy_connect.js
fixes #350 
@luin not sure if i missed something
=> Cluster lazy connect

lib/redis.js
Now it rejects with an `undefined`, which will cause warnings.
=> Reject with general error in Redis#connect

lib/redis.js
`CONNECTION_CLISED_ERROR_MSG` -> `CONNECTION_CLOSED_ERROR_MSG`
=> fix typo in error handler

README.md, lib/connectors/sentinel_connector.js, test/functional/sentinel.js
Option to specify a preferred slave (or slaves by priority) when connecting to a Sentinel group.
Fixes #38 .
=> Sentinel preferredSlaves option

.npmignore, package.json
Currently, the npm package contains the following:
```
benchmarks/
bin/
examples/
lib/
node_modules/
test/
.eslintrc
.npmignore
.travis.yml
API.md
Changelog.md
index.js
LICENSE
package.json
README.md
test_sentinel.js
```
Would it make sense to restrict it to the following?
```
lib/
Changelog.md
index.js
LICENSE
package.json
README.md
```
Edit: it should be easier than tracking each file :innocent: (https://github.com/luin/ioredis/pull/378/commits/1df3da92f72f252a0b0e70ba3983ead18027b985)
=> restrict files included in npm package

API.md, lib/cluster/index.js, lib/redis.js
=> perf: by default calling setNoDelay on the stream

lib/redis.js, test/functional/connection.js
I'm not sure if this is the right approach but the idea is to be able to quit immediately when `redis.quit()` is called and the client is in the reconnecting state. In this case, `quit()` should not have to wait for the connection to be ready.
What do you think?
=> Quit immediately when reconnecting

README.md, lib/connectors/sentinel_connector.js, test/functional/sentinel.js
Also add a few helpful notes to the README. This came from some frustrations I had the first time I setup a project to talk to sentinels.
=> Add a default port for sentinel connections.

lib/connectors/sentinel_connector.js, lib/redis.js
This is a quick fix to report on a sentinel cluster not being able to connect. 
This will also report retries in `redis.on('end', ...` for subsequent retries of the Sentinel cluster, this behavior is similar to what happens on a failed connection with a single redis instance.
This is the quickest fix I could think of.
=> fix: report error on Sentinel connection refused (#445)

lib/connectors/sentinel_connector.js
Hey there. It seems that when sentinels are IPv6-only, there's currently no way to connect to them: the "family" option doesn't apply. This PR fixes the situation.
=> Allow connection to IPv6-only sentinels

lib/pipeline.js
This copies the arguments for a multi command instead of mutating the passed in arrays. This allows users to log the commands that gave an error if the multi command errors.
=> stop mutating the arguments when calling multi

README.md
This P/R offers some minor changes to the README. Most importantly (to me, anyway) to add missing documentation for a helpful setting when connecting to a cluster.
* Adds README doc for `slotsRefreshTimeout`, added in https://github.com/luin/ioredis/pull/475
* And a minor formatting tweak / typo fix in the `startupNodes` example, also in the Cluster section of the README
Let me know if you have any feedback.  Thanks!
-Ben
=> Add documentation for slotsRefreshTimeout to README

lib/utils/index.js, test/unit/utils.js
Currently this method expects `hasOwnProperty` to exist on the passed object. By using the method on `Object.prototype` instead, objects created with `Object.create(null)` can also be properly handled.
Ran into this bug trying to pass graphQL input objects (heavily uses `Object.create(null)`) directly to hmset commands
=> Allow convertObjectToArray to handle objects with no prototype

package.json
In order to close a low-severity ReDoS vulnerability, the debug
module should be updated to at least v2.6.9
See https://nodesecurity.io/advisories/534 for more information
=> Update debug to v2.6.9

API.md, lib/redis.js, test/functional/connection.js
BREAKING CHANGE:
`Redis#connect()` will be resolved when status is ready
instead of `connect`:
```
const redis = new Redis({ lazyConnect: true })
redis.connect().then(() => {
assert(redis.status === 'ready')
})
```
=> feat: `Redis#connect()` will be resolved when status is ready

lib/cluster/connection_pool.js
Offline queue should be enabled on the internal cluster nodes so that we don't need to wait for the `ready` event before sending commands to the node.
That doesn't cause issue when the node is lost, since the `retryStrategy` is null, so when a node is lost, the status become `end` and the further commands will be rejected.
=>  fix(Cluster): issues when setting enableOfflineQueue to false

README.md, package.json
This change makes the description in the readme and on npm line up with the repo description.
io.js isn't even supported any more, and references to it make the project sound dated or unmaintained.
=> Remove io.js from description in readme and package.json

package.json
The changelog for 4.0.0 states that node <6 isn't supported so this updates package.json to reflect that.
=> Updated package.json to require node >=6

lib/cluster/index.ts
This commit will prevent status changes from 'disconnecting'
to 'connecting' and will stop connecting to a nodes
when disconnecting, which will make disconnecting faster.
=> perf(cluster): make disconnecting from cluster faster

lib/cluster/index.ts
The moved handler must update the targetSlot before tryConnection call to correctly choose the node that owns the slot.
=> Fix MOVED slot redirection handler

README.md, lib/cluster/ClusterOptions.ts, lib/cluster/index.ts, lib/cluster/util.ts, test/functional/cluster/nat.js, test/unit/cluster.js
=> feat(cluster): add NAT support

lib/cluster/ClusterOptions.ts, lib/cluster/index.ts, test/functional/cluster/connect.js, test/functional/cluster/dnsLookup.js
Closes #753.
Previously, exceptions caused by DNS resolving will not trigger any reconnections and fail silently. That makes errors much harder to be handled. This fix catches these exceptions and triggers a reconnection to keep the same behaviors as v3.
=> fix(cluster): handle connection errors by reconnection

README.md
Minor typo found while reading the README.
=> typo: proctected -> protected

lib/connectors/SentinelConnector/index.ts, lib/redis.js, test/functional/tls.js
Two options added: `enableTLSForSentinelMode` & `sentinelTLS`
=> feat: allow TLS when using Sentinel

lib/pipeline.js, test/functional/pipeline.js
https://github.com/luin/ioredis/issues/778
=> (#778) perf: add checking and loading scripts uniqueness in pipeline

lib/redis.js
=> feat: add retryTime option when redis server not ready

lib/cluster/ClusterSubscriber.ts
The errors will be caught by connection pool and a new election will be made when the current subscriber
is lost, so we can safely ignore these errors.
Fix #768
=> fix(Cluster): ignore connection errors for subscriber.

README.md, lib/cluster/index.ts, test/functional/cluster/connect.js, test/mocha.opts
=> fix: add second arg to "node error" to know which node failed

package-lock.json, package.json
Due to the distributed npm package not having `License` file embedded, the package contents shouldn't be used.
But one can install directly from the GH repository... and everything is 🎉 and ☀️ back again.
=> fix: use flexbuffer from GH with License

lib/command.ts, lib/pipeline.ts, package-lock.json, package.json
=> Removed flexbuffer dependency

lib/transaction.ts
Hello,
Sometimes, execResult return is undefined. In this case, we just have to return.
_Note: Commit updated._
Regards,
=> Sometimes execResult is undefined.

lib/command.ts, test/functional/send_command.js
This commit uses Buffer.byteLength() insteand of String#length to handle non-utf8 command names.
Close #862
=> fix: handle non-utf8 command name

lib/cluster/index.ts, test/functional/cluster/index.js, test/functional/cluster/moved.js, test/functional/cluster/pub_sub.js, test/functional/cluster/quit.js, test/helpers/mock_server.js
As discussed in #850, we should use a separate connection for refreshing slots to avoid conflict with blocking commands invoked by users.
There are three tests failed in these changes. Still need some investigations.
=> fix(cluster): make blocking commands works with cluster

lib/transaction.ts, test/functional/cluster/transaction.js
`Pipeline#exec()` is a little tricky: it has an init process when called first time (indicated by whether `Pipeline#nodeifiedPromise` is true). `Transaction#exec()` is similar to that, it also has an init process that parse the result from `Pipeline#exec()` before returning to users. However, `#nodeifiedPromise` is not checked here, so it may fail which causes the unhandled warnings when retries.
Closes: #883.
To be frank, it also take me a lot of time in order to understand the code, especially the complex relation between Pipeline & Transaction. We indeed need to do a refactor on this.
=> fix: pipeline with transactions causes unhandled warnings

lib/cluster/index.ts, test/unit/cluster.js
Addresses the issue noted in https://github.com/luin/ioredis/issues/883#issuecomment-499959143
=> fix(cluster): reorder defaults arguments to prioritize user options

API.md, README.md
Document `dnsLookup` attribute to `Cluster` constructor.
Fixes #892.
=> Update API doc and README regarding dnsLookup attribute

examples/custom_connector.js, lib/redis/RedisOptions.ts, lib/redis/event_handler.ts, lib/redis/index.ts
Fixes https://github.com/luin/ioredis/pull/907#issuecomment-505545220
Realized that options was being passed through from an internal object, not the one I passed in, hence internal instantiation is needed.
=> Use connector as class not value

lib/connectors/SentinelConnector/index.ts, lib/connectors/StandaloneConnector.ts, test/functional/connection.ts
There's a race condition when making connections in 4.11.x,
which will happen easier with Bluebird & Unix socks.
Thank you to @jeremytm & @p3x-robot.
Close #918
=> fix: ETIMEDOUT error with Bluebird when connecting.

lib/cluster/index.ts, test/functional/cluster/duplicate.ts
Hi,
See https://github.com/luin/ioredis/issues/921. This PR adds the missing `cluster.duplicate()` method.
Notes:
- I'm using `this.startupNodes.slice(0)` to ensure we pass a copy and not a reference. This matches the behavior of the options, which also get a copy thanks to `Object.assign()`.
- I'm not sure this new test I added is being executed when running `npm test`. I don't see it in the mocha output. It works as expected when I run ` npx mocha test/functional/cluster/duplicate.ts`, could someone please validate?
=> feat: add cluster.duplicate() method

README.md, lib/redis/index.ts, lib/utils/index.ts, test/unit/utils.ts
Support [`rediss://` URL](https://www.iana.org/assignments/uri-schemes/prov/rediss) (Redis over TLS) by defaulting option `tls: true` for those URLs.
Fixes #846
=> Supports rediss:// URL

lib/redis/index.ts, lib/utils/index.ts, test/unit/redis.ts, test/unit/utils.ts
Fix #940. Alternative to #942.
=> fix: Don’t clobber passed-in tls options with rediss:/ URLs

README.md
=> docs(readme): fixes typo

lib/pipeline.ts
Execution cost of Pipeline.exec can be reduced to 50% or lower. This is
accomplished by first filling up an Array of Buffers and then calling `Buffer.concat`
instead of calling `Buffer.concat` for each command.
In our use-case (~3000 commands in a single Pipeline) wall-clock-runtime went
down from 1.3sec to 500ms.
=> Improved performance of Pipeline.exec

lib/connectors/SentinelConnector/index.ts
For TypeScript users, it is currently not possible to return an invalid delay in the `sentinelRetryStrategy` option.
The documentation says:
> If `sentinelRetryStrategy` returns a valid delay time, ioredis will try to reconnect from scratch.
So, I was curious what valid actually means here. It turns out, that a valid delay is any `number`.
```ts
const error = new Error(errorMsg);
if (typeof retryDelay === "number") {
setTimeout(() => {
resolve(connectToNext());
}, retryDelay);
eventEmitter("error", error);
} else {
reject(error);
}
```
[Link](https://github.com/luin/ioredis/blob/4bce38b28a8f31f552bb3fce44ca0f413435d2c2/lib/connectors/SentinelConnector/index.ts#L112-L120) to the mentioned code.
However, the problem is that the `sentinelRetryStrategy` can either be `undefined` in …
=> Allow sentinelRetryStrategy to be disabled

lib/redis/index.ts
When send command not in `redis-commands`, it may raise exception 'Unknown command' when `status` not 'ready'.
=> fix: prevent exception when send custom command

lib/cluster/index.ts
When some nodes disconnected from the cluster, there will be left with some empty addresses.
Then the `CLUSTER SLOTS` will reply with empty hosts.
`ioredis` then convert the empty address `:0` to `127.0.0.1:6379` internally and try to connect them.
Even worse, when `scaleReads=='slaves'`, it may try to sendCommand to `:0`.
So we'd better just ignore these empty addresses.
=> Ignore empty hosts returned by CLUSTER SLOTS

README.md, examples/basic_operations.js
This change only affects the project documentation.
This change adds more details to the basic example. These details show a new user what to expect from the library. 
As a beginning user of this library, I didn't know what the basic functions returned until I set up a redis server and a notebook to test it out myself. I want to 
I tested the proposed file changes at https://runkit.com/barakplasma/ioredis-basic-operations .
=> docs: add more detail to the basic example

README.md
=> docs(README): Formatted Cluster docs

lib/cluster/index.ts, lib/command.ts, lib/commander.ts, lib/script.ts, test/functional/cluster/index.ts, test/functional/maxRetriesPerRequest.ts
This introduces a new option for defineCommand: readOnly
It tells ioredis that this command is safe to be executed on slaves and allows the option scaleReads to also apply to the custom command.
=> feat: ability force custom scripts to be readOnly and execute on slaves

examples/basic_operations.js, lib/command.ts, lib/pipeline.ts, lib/redis/event_handler.ts, test/functional/elasticache.ts, test/functional/reconnect_on_error.ts, test/helpers/mock_server.ts, test/unit/pipeline.ts
Elasticache severs the connection immediately after it returns a
READONLY error.  This can sometimes leave queued up pipelined commands
in an inconsistent state when the connection is reestablished. For
example, if a pipeline has 6 commands and the second one generates a
READONLY error, Elasticache will only return results for the first two
before severing the connection. Upon reconnect, the pipeline still
thinks it has 6 commands to send but the commandQueue has only 4. This
fix will detect any pipeline command sets that only had a partial
response before connection loss, and abort them.
This Elasticache behavior also affects transactions. If reconnectOnError
returns 2, some transaction fragments may end up in the offlineQueue.
This fix will check the offlineQueue for any such …
=> Elasticache: Abort incomplete pipelines and transactions upon reconnect

README.md
The existing README code sample checks for an error message that begins
with the string READONLY however if the error is produced from a lua
script the condition would not match it. A lua script READONLY error
looks like this:
```
127.0.0.1:7000> eval "redis.call('set', 'foo', 'bar')" 0
ERR Error running script (call to f_45e87c07f6aff394093b73766a458691d0460655): @user_script:1: @user_script: 1: -READONLY You can't write against a read only replica.
```
This changes the sample to instead check for READONLY as a substring
=> Adjust README reconnectOnError code sample

lib/redis/index.ts, test/functional/connection.ts
It's possible for connect promise to resolve after the resolved
connection has already been established, which means we miss the connect
event. This can happen when Bluebird is set as the global Promise, and
we connect to an ip address host for example. This fix checks to see if
that's the case and invokes the connection handler directly. Thanks
@luin for the recommendation.
Fixes #977
=> Handle connection after connect event was emitted

lib/pipeline.ts, test/functional/pipeline.ts
Hello, I want to report a bug in the `pipeline.ts` and submit the bug fix as well.
---
In the script checking part:
```js
return this.redis
.script('exists', Array.from(new Set(scripts.map(({ sha }) => sha))))
.then(function (results) {
var pending = [];
for (var i = 0; i < results.length; ++i) {
if (!results[i]) {
pending.push(scripts[i]);
}
}
```
It will pass a **uniqued scripts array** (`Array.from(new Set(scripts.map(({ sha }) => sha)))`) into `SCRIPT EXISTS`, this is fine.
However it will add the scripts from the **original scripts array** (`pending.push(scripts[i])`), this could introduce a problem.
The bug seems to be introduced since #781.
---
If I defined 2 custom commands `echo` and `test`, and do:
```js
redis.pipeline()
.echo()
.echo()
.test()
```
Then the `scripts` will …
=> Fix bug that scripts may not be loaded correctly in pipeline

examples/basic_operations.js, lib/cluster/ClusterSubscriber.ts, lib/cluster/util.ts, lib/connectors/SentinelConnector/index.ts, lib/redis/RedisOptions.ts, lib/redis/event_handler.ts, lib/redis/index.ts, lib/utils/index.ts, package.json, test/functional/auth.ts, test/unit/utils.ts
This PR contains the following changes:
- Adds the `username` optional key to the `IRedisOptions` interface and instantiation options.
- Adds 2 extra error handlers for handling Redis 6 default user not needing password and user passing username and password to a Redis <=5 instance (https://github.com/luin/ioredis/pull/1130/files#diff-43fd638f7be3d3664e2c4ee36dbdf059R32-R50)
- Update URL parser to handle for username passed in redis URL
- Tests for redis 5 and redis 6 using the new auth code.
Fixes luin/ioredis#1097
=> Adds auth support for Redis 6

lib/utils/index.ts, test/functional/auth.ts, test/unit/utils.ts
Closes #1132.
Previously, users can specify the username in Redis connect URI unintentionally so parsing username leads potential breaking changes in this case. We still support `username` parameter so users can opt-in ACL explicitly.
=> fix: revert parsing username via URI due to potential breaking changes

lib/redis/index.ts
This super simple PR fixes #1126, an issue which occurs when encountering `INFO` response field values containing the colon character.
The purpose of this patch is to have the exposed `serverInfo` client property fully conformant with potential unexpected values Redis can respond with.
I understand that the `serverInfo` property is not documented, though it has apparently come into direct use by external libraries. I'm curious what the official stance on this is, and if this should be considered a valid practice or rather a misstep.
=> Fix _readyCheck INFO parser's handling of colon characters

lib/cluster/index.ts, lib/redis/index.ts, test/functional/cluster/connect.ts, test/functional/connection.ts
Hi,
This PR has been opened following the issue #1138.
It might also fix #1007 (not tested).
Thank you for your time!
=> [reconnect] fixes #1138

lib/cluster/ClusterOptions.ts
Only `address` seems to be required.
=> Correctly type dns callback

.travis.yml, lib/autoPipelining.ts, package-lock.json, package.json, test/functional/cluster/autopipelining.ts
[x] Fixes a severe autopipeline bug that prevented correct routing.
[x] Fixes #1216 by downgrading `p-map` to `2.1.0`, which is the last one that supports Node 6.
[x] Changes the Travis matrix to run against all Node even version >= 6, plus the current unstable one.
The autopipeline bug was not catch from the test suite since testing for cluster goes against a mock cluster.
Shall we change this to test against a real cluster?
=> fix: Fix autopipeline and downgrade p-map to support Node 6. [#1216]

README.md
Found a typo in readme where it said `stream#pause()` instead of `stream.pause()`
=> Fix typo for stream in README.md

lib/autoPipelining.ts
The auth command should be sent before other commands.
So it should be exclude from auto pipeline command list as well.
The issue is related to #1238
=> fix: auth command should be not allowed in auto pipeline.

lib/cluster/index.ts, lib/redis/index.ts
After calling `redis.quit` there are still many open `setInterval` handles that have not been cleared.
These uncleared `setInternal` appear to be because everytime `connect` is called in the `reconnectTimeout` the `this._addedScriptHashesCleanInterval` is overridden by the old one, which is still running in the background.
https://github.com/luin/ioredis/blob/v4.19.2/lib/cluster/index.ts#L311-L313
When you call `redis.quit` it only clears the current one retained by `this._addedScriptHashesCleanInterval`.
```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
- fd 1 (tty) (stdio)
- fd 0 (tty)
- fd 2 (tty) (stdio)
- Intervals:
- (60000 ~ 60 s) (anonymous) @ /srv/app/node_modules/ioredis/built/redis/index.js:258
- (60000 ~ 60 s) (anonymous) @ …
```
=> Prevent duplicate intervals being set.

API.md
It seems like some markdown doesn't work inside of `<dt>` HTML table tags in the github UI?
=> Fix formatting in API.md

README.md
The reconnectOnError handler doesn't necessarily execute on newer configurations of AWS ElastiCache infrastructure, particularly those with auto-failover enabled.
The testing methods mentioned in the changes are repeatable, but it's hard to say how they compare to a "real" failover event versus a simulated one.
=> Update failover docs for AWS ElastiCache

README.md, lib/utils/index.ts, test/functional/auth.ts, test/unit/utils.ts
This PR adds username support for URI. It was reverted in #1134 for compatibility reasons. In this PR we added a parameter `allowUsernameInURI` for users to enable this explicitly.
=> feat: support username in URI

README.md, lib/ScanStream.ts, test/functional/scan_stream.ts
=> Add type support for scanStream

lib/pipeline.ts
Closes #1288
There's already a property `isCluster` so we should just use it. The string detection is kept for BC and will be removed in the next major version.
=> Fix cluster issues when code is processed by babel

lib/command.ts
`hset` and `hmset` have the same logic when processing parameter conversion, so use the same function variable to reuse the same processing.
=> Reuse the  args logic of `hset` and `hmset`

README.md, lib/cluster/ClusterOptions.ts, lib/cluster/index.ts, test/functional/cluster/moved.ts
When a MOVED response is received from the cluster resend the commands using a delayed queue
=> Use delay queue for commands in case of MOVED response.

package-lock.json
We should probably disable package-lock.json as npm ignores locks inside a module, and that will make our local dev env not get the same dependency versions as end-users will get.
=> Recreate package-lock

lib/pipeline.ts, test/functional/pipeline.ts
Fixes #1303
Support parallel .multi script execution by delaying the assignment of the load confirmation.
btw. regarding the project setup: the package-lock.json links to `http://artprod.dev.bloomberg.com/artifactory/api/npm/npm-repos/` as npm registry, which isn't publicly available. Therefore `npm install` and `npm ci` fails locally. By replacing all the urls with the npm registry, the npm install works again.
=> fix: support parallel script execution in pipelines

package-lock.json
Closes #1308
TypeScript 3.9 changes the export signatures that cause some compatibility issues. This PR downgrade it to 3.8.3 to solve the issue. We'll consider TypeScript upgrade as a breaking change so will include it in the next major version.
=> fix: minor compatibility issues caused by TypeScript upgrade

lib/redis/event_handler.ts, test/functional/connection.ts
=> fix: select db in cluster mode causes unhandled errors

lib/connectors/SentinelConnector/index.ts, lib/connectors/StandaloneConnector.ts, test/functional/tls.ts, test/unit/connectors/connector.ts
Change TLS options to be consistent across the library and align with `tls.connect()` parameter types.
Allows sentinel connections to use all available TLS options. Right now the typings won't allow you to use the full range of TLS options for `sentinelTLS` that `tls.ConnectionOptions` provides.
**Currently:**
```typescript
const redis = new ioredis({
sentinels: [{
host: 'localhost',
port: 26379,
}],
name: 'mymaster',
sentinelTLS: {
servername: 'localhost', // <- NOT ALLOWED, type error
},
});
```
```typescript
const redis = new ioredis({
host: 'localhost',
port: 6379,
tls: {
servername: 'localhost', // <- ALLOWED
},
});
```
`ConnectionOptions` is used by `tls.connect()`
```typescript
function connect(options: ConnectionOptions, secureConnectListener?: () => void): TLSSocket;
``` …
=> use tls.ConnectionOptions instead of tls.SecureContextOptions

.eslintrc.yml, .travis.yml, package-lock.json, package.json
As Node.js v6 is still officially supported, it should probably be tested against in Travis.
As far as I know, the only blocker is mocha 7, which dropped Node 6 support. However, mocha 6 seems to be working fine with this project as well. I guess we'll see what happens when Travis checks this PR.
=> Added Node.js v6 to Travis conf, downgraded mocha to 6.2.3

lib/cluster/ClusterSubscriber.ts, lib/cluster/index.ts, lib/cluster/util.ts, test/functional/cluster/ClusterSubscriber.ts, test/functional/cluster/pub_sub.ts, test/helpers/mock_server.ts
This PR fixes #1325:
1. Close existing subscriber connections before selecting a new one.
2. Use the connection name provided in options for internal connections.
To test:
1. Make sure the leaking issue is fixed.
2. Make sure the connection names for refresher and subscriber are correct.
=> Fix cluster subscriber connection leaking

lib/connectors/SentinelConnector/FailoverDetector.ts, lib/connectors/SentinelConnector/index.ts, lib/connectors/SentinelConnector/types.ts, lib/redis/RedisOptions.ts, lib/redis/index.ts, test/functional/sentinel.ts, test/helpers/mock_server.ts, test/helpers/once.ts
Fixes #1314
While working on this, I forgot about the `lastActiveSentinel` suggestion from the other issue. At this point, I'm not sure if it's needed, but I can still add it if it is.
I've tested this with various failure scenarios in a Docker cluster and it successfully reconnected in all of them. I also simulated many of the scenarios in new test cases.
=> Detect failover from +switch-master messages

lib/command.ts, lib/redis/index.ts, lib/utils/index.ts, test/functional/commandTimeout.ts
Currently, using the `commandTimeout` option is creating one timer per command and they're not being cleared as each command gets fulfilled. This PR does that.
=> clears commandTimeout timer as each respective command gets fulfilled

API.md, lib/autoPipelining.ts, lib/commander.ts, lib/pipeline.ts, test/functional/autopipelining.ts, test/functional/cluster/autopipelining.ts, test/functional/pipeline.ts, test/unit/commander.ts
A fix for https://github.com/luin/ioredis/issues/1228
Also came across https://github.com/luin/ioredis/issues/621 whilst looking into this, and realised similar issue could exist for commands created via createBuiltinCommand, i added a suggested addBuiltinCommand to fix this.
=> Fix autopipeling for buffer function + added built in commands

benchmarks/errorStack.ts, lib/command.ts, lib/commander.ts
Improving Error stack serialization performance when `showFriendlyErrorStack=true`.
With current implementation there's about 30% overhead because the stack trace is serialized even when it's not actually needed.
With proposed change the overhead is somewhere between 1-5% on Node 14. There were improvements related to stack trace serialization in Node 12.
On the attached benchmark results, first run is on old code, second run on new code. Benchmark code also committed.
=> perf: Serialize error stack only when needed

lib/connectors/SentinelConnector/index.ts, lib/redis/RedisOptions.ts, lib/redis/index.ts, test/functional/sentinel.ts
There is an issue related to connections used for active failover detection for sentinels not being cleaned up properly: #1362. Given that not many users realize the usefulness of this feature, and the feature does create more connections, we disable it by default and allow users to enable it with the option`failoverDetector`.
=> fix(SENTINEL): disable active failover detection by default

lib/command.ts, test/functional/hgetall.ts
=> fix: handle malicious keys for hgetall

lib/command.ts, test/functional/hgetall.ts
As mentioned in https://github.com/luin/ioredis/issues/1417
=> fix: improve proto checking for hgetall [skip ci]

lib/autoPipelining.ts
Seen in an uncaughtException handler with ioredis 4.27.7
The application having this issue has a constant&high volume of redis calls, and is using both Redis and Redis.Cluster clients to connect to different redis servers. So it might be related to redis cluster. Or newrelic, but I doubt it, processImmediate is something I'd guess would be from the setImmediate call?
This is happening throughout the day
```
err_type=uncaughtException, exiting cause=TypeError: Cannot read property 'Symbol(callbacks)' of undefined
at Immediate.executeAutoPipeline (.../node_modules/ioredis/built/autoPipelining.js:34:31)
at Shim.applySegment (.../node_modules/newrelic/lib/shim/shim.js:1430:20)
at Immediate.wrapper (.../node_modules/newrelic/lib/shim/shim.js:2097:17)
at processImmediate …
```
=> Fix undefined property Error in executeAutoPipeline

lib/autoPipelining.ts, lib/pipeline.ts, lib/transaction.ts, test/functional/cluster/autopipelining.ts, test/functional/lazy_connect.ts
=> fix(cluster): lazyConnect with pipeline

lib/autoPipelining.ts
Deliberately add `asCallback` on the **same** Promise instance being returned,
not on a different Promise instance that resolves to the same thing.
Avoid this category of unhandledRejection errors:
```javascript
process.on('unhandledRejection', (reason) => console.log('unhandledRejection', reason));
const x = Promise.reject(new Error());
x.catch((e) => console.log('caught x', e));
const causesUnhandledRejection = Promise.resolve().then(() => x);
```
Related to #1466
=> Handle possible unhandled promise rejection with autopipelining+cluster

lib/pipeline.ts
1. Always return the same Promise in pipeline.exec.
An example of why the original Promise should be returned, rather than
a different Promise resolving to the original Promise:
```javascript
process.on('unhandledRejection', (reason) => console.log('unhandledRejection', reason));
const x = Promise.reject(new Error());
x.catch((e) => console.log('caught x', e));
const causesUnhandledRejection = Promise.resolve().then(() => x);
```
2. In the negligible chance the `script exists`/`script load` command
failed, give up, catch the rejected Promise with `finally`,
and try to run the commands in the pipeline anyway.
(e.g. networking issues, corrupted bytes, misbehaving proxy/server, etc)
This isn't the best approach, but it's hopefully better than an unhandled Promise rejection,
resource/memory …
=> fix: unhandled Promise rejections in pipeline.exec [skip ci]

lib/autoPipelining.ts
Set kCallbacks field to null instead of the empty array because nothing
should append to it until a new pipeline starts.
If anything did, that is a bug.
With Redis.Cluster, there could be 16384 different arrays pointing to
callbacks that aren't needed.
Memory impact probably isn't significant if those all point to Promises to resolve/reject,
though I guess the resolved data could itself be large in some cases
=> fix: fix a memory leak with autopipelining.

test/functional/scan_stream.ts, test/helpers/util.ts
See https://redis.io/commands/scan
When this test fails in local development
it stops the rest of the tests from running.
Some OSes (versions) have redis 5 or older installed.
=> scanStream TYPE test requires redis 6

README.md
Fix a dead link caused by the destination hash having changed.
=> Fix API documentation link

lib/DataHandler.ts
when works with the new server assist client side cache feature, redis sends single string "\_\_redis\_\_:invalidate" from server.
so reply[2] is null, the update fixes the issue
=> fix reply[2] is null issue

lib/cluster/index.ts, lib/redis/event_handler.ts, lib/redis/index.ts, test/functional/autopipelining.ts, test/functional/cluster/autopipelining.ts, test/functional/cluster/disconnection.ts, test/functional/disconnection.ts
=> Make sure timers is cleared on exit

lib/redis/index.ts, test/functional/pipeline.ts
Lua scripts get loaded once and not retried unless a client side interval expires: https://github.com/luin/ioredis/blob/master/lib/pipeline.ts#L376
This causes issues with redis instances restarting or failing over.
There's no way of knowing whether a script is still present in the new instance.
We should reset the local state and just load them again when a reconnect happens and rely on the existing code that checks whether the scripts are present on the server.
~I ran into that issue while testing the reliability of a service, but it might also fix https://github.com/luin/ioredis/issues/1405~ See #1499 for the cluster fixes.
There's still a small time window where `NOSCRIPT` errors occur as messages are already queued for execution. ~Previously the script handler only executed `EVAL` in …
=> Fix script loading behavior on script flush with pipelines

.eslintrc.json, lib/Redis.ts, lib/redis/event_handler.ts, package-lock.json, package.json, test/functional/connection.ts, test/functional/monitor.ts, test/functional/pipeline.ts, test/functional/ready_check.ts
Closes #1293
Closes #1211
BREAKING CHANGE: `Redis#serverInfo` is removed. This field is never documented so
you very likely have never used it.
=> feat: skip ready check on NOPERM error

lib/Pipeline.ts, lib/Redis.ts, lib/Script.ts, lib/cluster/index.ts, test/functional/pub_sub.ts, test/functional/scripting.ts
@luin here are some micro-optimizations we can take in v5. Just close it if you don't like it 😉 
- Prevent unnecessary buffer allocations when using string and buffer commands in one pipeline.
The performance is almost negligible, but I think the code is also a bit more explicit as it strictly separates buffer and string operations.
- Use `error.message` instead of `error.toString()`. Not sure whether it was there for legacy reasons
- Remove unnecessary `queue.length` checks, as `queue.shift()` basically does the same
- Use a more explicit control flow in Redis#sendCommand to improve readability
=> More explicit control flow

lib/Command.ts, lib/Script.ts
It was introduced to prevent sending custom commands in cluster+pipeline: https://github.com/luin/ioredis/blob/80f4a454fb0d24392e4fa27fbd3f6f22b0bf938e/lib/pipeline.js#L250, and it's not used anymore.
Make sure the property is not used anymore.
=> fix: remove unused Command#isCustomCommand

bin/generateRedisCommander/index.js, bin/generateRedisCommander/returnTypes.js, bin/generateRedisCommander/typeMaps.js, lib/utils/RedisCommander.ts, test-d/commands.test-d.ts
Closes #1429.
Changes:
1. Improved typings for `smismember` so it returns `number[]` instead of `unknown[]`.
2. Improved typings for`geopos`, `lmpop`, `blmpop`, `bzpopmin`, `bzpopmax`, and `xread`.
3. Make the declaration order stable to make further diffs easier.
5. Make numeric parameters also accept strings. Otherwise, it was a little tricky to figure out where the issue was (the correct fix was to change `'1000'` to `1000`):
=> feat: improve typings for smismember

lib/cluster/index.ts, lib/index.ts
Expose typings that @types/ioredis exports so users don't need to define their own. No prod code changes.
=> fix: improve typing compatibility with @types/ioredis

README.md
The current Redis sentinel url in README not working and you encounter a 404 page on the Redis documentation website and the Sentinel documents URL has changed which I updated the README.
=> Update redis sentinel doc URL

lib/redis/RedisOptions.ts
Closes #1550
No actual code changes. Just types.
=> fix: allow option maxRetriesPerRequest to be null

bin/overrides.js, lib/utils/RedisCommander.ts, test/functional/transformer.ts, test/typing/transformers.test-d.ts
Closes #1536
There is a limit on the TypeScript side https://github.com/microsoft/TypeScript/issues/15300#issuecomment-891681234 that you can't assign an interface to a record:
```ts
interface User {
name: string;
age: string;
}
let newUser: User = {
name: "suman",
age: "34",
};
const record: Record<string, string> = newUser; // Error here
```
Given `hmset` and `mset` already support ES6 `Map`, I think it's should be fine to loosen the typing here for convenience.
It's possible that developers may pass invalid object values (e.g. `redis.hmset("user-hash", new WeakMap([[{ name: "Bob" }, "value"]]))`) but I think that's fine since the usage doesn't make sense and it will trigger an runtime error anyway.
=> fix: support TypeScript interface as parameters of hmset and mset

lib/Redis.ts, lib/connectors/SentinelConnector/index.ts, lib/connectors/StandaloneConnector.ts
I haven't tested it yet as I'm running on macos and there's no way to read out the socket options, but this should fix #1339
- 🐛 Call `socket.setKeepAlive(true, ms)` after a successful connect as workaround for a node issue where it won't work when it's called before a successful connect
=> Hook up the keepAlive after a successful connect

lib/Redis.ts, lib/redis/event_handler.ts, package-lock.json, package.json, test/functional/monitor.ts
Closes #1498
The cause was `self.call('monitor')` not being caught and unhandled errors crashed the process.
Test Plan:
1. Create a new user on Redis without the permission of `monitor`:   `ACL SETUSER nomonitor reset +info >123456 on`.
2. Make sure with user `nomonitor`, calling `redis.monitor()` should be rejected.
=> fix: handle NOPERM error for monitor

bin/template.ts, lib/cluster/ClusterOptions.ts, lib/index.ts, lib/redis/RedisOptions.ts, lib/utils/RedisCommander.ts, test/typing/options.test-d.ts
Closes #1559
No actual code changes.
=> Expose ChainableCommander and other types

lib/transaction.ts, test/typing/pipeline.test-d.ts
=> fix: improve typing for redis.multi

README.md
The dollar sign was getting copied along with the npm commands when clicked on copy code button on GitHub thus resulting in bash error. Removed the $ sign to prevent this.
=> docs: (README) removed $ from npm commands

bin/template.ts, lib/Pipeline.ts, lib/utils/RedisCommander.ts, test/typing/pipeline.test-d.ts
=> fix: Add back Pipeline#length

lib/cluster/ClusterSubscriber.ts, test/functional/cluster/pub_sub.ts
We ran into an issue where some of our redis clients would miss messages from the pubsub bus following a network issue / crash in the redis cluster. This PR changes the reconnect logic in the ClusterSubscriber such that it can pick to connect to a different node when the current connection closes. The idea being that if a single node is having issues, the subscriber can connect immediately to another member of the cluster so it doesn't miss as many messages.
=> fix: always allow selecting a new node for cluster mode subscriptions when the current one fails

bin/returnTypes.js, lib/utils/RedisCommander.ts, test/typing/commands.test-d.ts
The result of zscore can be null if member or key does not exist.
```ts
const result = await redis.zscore("key", "member") // return string or null
```
https://redis.io/commands/zscore/
=> fix: type of zscore result should be nullable

lib/utils/index.ts, test/unit/redis.ts, test/unit/utils.ts
Node 18 stopped coercing the type for its options (specifically the ip family option) and instead throws an error. So if you pass in `?family=6` in your Redis URL, it would fail because when it does the DNS lookup passing in the string `'6'`, node would throw an error.
Fixes https://github.com/luin/ioredis/issues/1672
=> Fixes passing in family parameter in URL in node 18

test/functional/monitor.ts, test/functional/pipeline.ts, test/functional/scripting.ts
Allow [dragonfly](https://github.com/dragonflydb/dragonfly) to successfully pass tests
This include changes only to the test code!.
This include two changes:
1. Compare result from the monitor to be case insensitive. 
2. The order of the result from the monitor can be out of order.
The reason being - 
In dragonfly the processing of the monitor command in no done single threaded (Redis is single threaded). This means that commands can and will process in parallel and that the name of the commands are changed to upper case (as they are pass between threads). As a result the command that the monitor returning would be in the case of dragonfly in upper case always, and the processing order in not deterministic as in Redis - process is done in parallel. 
Adding these changes would make this …
=> test(functional): monitor result compare lowercase

README.md
👋 Hello, when upgrading my version of ioredis from v4 to v5 I noticed a desync in the Readme
[Breaking changes](https://github.com/luin/ioredis/blob/main/CHANGELOG.md#breaking-changes) include that 
> `slotsRefreshInterval` is disabled by default, previously, the default value was 5000.
In the [Readme](https://github.com/luin/ioredis#cluster), it is still mentioned that its default value is 5000
=> docs: update readme to fix slotsRefreshInterval default value

lib/index.ts
Currently getting a "has no construct signatures" error with the following in Typescript 4.9.4, Node 18.12.1, type: module, module: node16, moduleResolution: node16:
```ts
import Redis from 'ioredis'
const redis = new Redis()
```
Changing the ioredis package with this change allows:
```ts
import { Redis } from 'ioredis'
const redis = new Redis()
```
without any error, and with full type information.
=> fix: add named export to support ESM imports in Typescript

lib/connectors/StandaloneConnector.ts
Node 18 introduced a new `keepAlive` option in the TCP socket constructor.  
This causes ioredis's TypeScript typings to clash with `@types/node`, because we define `keepAlive` as `number | undefined`, whereas Node defines it as a `boolean`.  
Luckily, this isn't a runtime regression.  We don't pass `keepAlive` into `createConnection`, and in fact only pass in three properties total.  _But_ we pretend that any property of `TcpNetConnectOptions` can be included in `RedisOptions`.  
This PR reduces the surface-area of `RedisOptions` to only include the TCP and IPC connection parameters that we actually use, which results in `keepAlive` once again having the correct TS type.
It should also be less confusing for users, as we've removed several unused properties off of that interface...
Fixes …
=> remove extraneous TCP/IPC properties from RedisOptions TS type

lib/Redis.ts
This fixes an error we are running into. In our code base we have a system that will mock out dependencies. However it iterates over props to stub out functions. In this process it accesses this getter property. Before connect is called this getter tries to access `this.condition` which is undefined so accessing the property of it causes a crash in ioredis. This handles that case so ioredis does not try to access property `subscriber` of undefined.
=> fix: check that condition is defined before we access it

.github/workflows/release.yml
Previously, the release process is triggered on every commit added on the main branch. A drawback is that the approach could release too many versions and it's hard for users to keep track of release notes.
This PR changes the release process to be manually.
=> chore: Release new versions manually

lib/Command.ts, lib/DataHandler.ts, lib/SubscriptionSet.ts, lib/cluster/ClusterSubscriber.ts, lib/redis/event_handler.ts, test/functional/cluster/spub_ssub.ts, test/functional/spub_ssub.ts
since redis 7.0 add SSUBSCRIBE/SPUBLISH/SUNSUBSCRIBE to support  shardchannel .some developer also need this [[Feature Request] Redis 7 shard pub/sub support #1588](https://github.com/luin/ioredis/issues/1588)，this commit is to solve this. @luin
=> feat: add support ssubscribe

.github/workflows/test.yml, test/functional/monitor.ts, test/functional/scan_stream.ts, test/functional/transformer.ts, test/helpers/util.ts
Given that almost all Redis features are added in a backward-compatible way, we will only test against the latest Redis version to make test cases easier to maintain.
=> test: Run tests against latest Redis

lib/DataHandler.ts, test/functional/pub_sub.ts
=> Fix unsubscribe not work with stringNumbers

lib/Redis.ts, test/typing/events.test-.ts
help callback of pub/sub typed
https://github.com/luin/ioredis#pubsub
=> add type for known event of EventEmitter

examples/hash.js
`hmset` is deprecated, so I've replaced it with `hset` in this example code.
Ref: https://redis.io/commands/hmset/
=> Update hash.js example from deprecated hmset -> hset

README.md
I know it's a section about a specific command in Redis, and I don't know if this library wants to document all Redis commands.
But, as a user of this library, in my research about how I can expire my keys using ioredis, I tried to search on the docs words like "expires", "expiration", and I can't find anything, so I googled and searched on issues to finally find my answer on this issue #159 
I think creating this section will be useful for those who want to use timeout in Redis, one of the most used Redis features for people who use Redis for caching, and I think adding a simple section about it will help those users (like me), which searches on "expiration" words and finds nothing in the docs.
I know you can find it just by searching about "EX", but some users don't mind this, or don't …
=> Create a section about expiration time on keys

README.md
=> Migrate repo links

lib/DataHandler.ts, test/functional/socketTimeout.ts, test/unit/DataHandler.ts
The issue occurs when using socketTimeout, causing connections to become unstable with repeated disconnections and reconnections. This happens due to incorrect ordering of socket stream event handling.
Changes:
- Use prependListener() instead of on() for `DataHandler` stream data events
- Explicitly call resume() after attaching the `DataHandler` stream listener
- Add tests to verify socket timeout behavior
This ensures the parser receives and processes data before timeout checks, preventing premature timeouts and connection instability.
Fixes #1919
=> fix: Connection instability when using socketTimeout parameter

README.md, lib/cluster/ClusterOptions.ts, lib/cluster/index.ts, lib/connectors/SentinelConnector/index.ts, test/functional/cluster/nat.ts, test/unit/clusters/index.ts
The feature need when cluster nodes connected through dedicated subnet and you dont know exact host - only port
Also it would be useful if node failing and changing ip address
Changes:
- Extend NatMap Type - union with object(previous) and function  
- Extend natMapper in Cluster for also work through function if it specified
- Extend sentinelNatResolve in SentinelConnector for also work through function if it specified
Maybe fixes: https://github.com/redis/ioredis/issues/1003
=> feat: Add ability for nat mapping through function

README.md, lib/cluster/index.ts
Adding the option for disabling slots refresh by setting the slotsRefreshInterval option to a negative value, similar to https://github.com/redis/ioredis/commit/370fa625cd20bfe62f41c38088e596c7a6f0619c#diff-bf62b2774a434c4a07716686a3c1fbd23368a673a7633622bdf1a9a9cd087de5
Backported bugfix: when `refreshSlotsCache` is called concurrently, call the callback only when the refresh process is done #1881
=> feat: added the option for disabling slots refresh, fixed concurrent calls to refreshSlotsCache

lib/cluster/index.ts
If Redis fails at that branch, Redis will swallow the error and give a generic `ClusterAllFailedError: Failed to refresh slots cache` error. Generally this error provides the actual reason for failure, e.g. invalid credentials.
This diagnostic can probably resolve most issues related to `ClusterAllFailedError: Failed to refresh slots cache`:
Fixed: https://github.com/redis/ioredis/issues/1800, https://github.com/redis/ioredis/issues/1454, https://github.com/redis/ioredis/issues/1415, https://github.com/redis/ioredis/issues/1103, https://github.com/redis/ioredis/issues/1003, https://github.com/redis/ioredis/issues/1062
=> fix: Log Cluster.SLOTS errors on initial connection

bin/returnTypes.js, lib/utils/RedisCommander.ts, package-lock.json, package.json, test/functional/hexpire.ts
Implement `hexpire` command for https://github.com/redis/ioredis/issues/1898
Will require an update to `@ioredis/commands` from this PR https://github.com/ioredis/commands/pull/3
=> Implement hexpire for #1898

.github/workflows/release.yml, .releaserc.json
Assigns the v4 branch its own dist-tag (`v4`) and restricts it to the 4.x version range. This prevents v4 maintenance releases from overwriting the latest major version in the default npm channel.
#1974
=> chore(release): stop overwriting npm `latest` dist-tag

.github/workflows/stale-issues.yml
**Added Dual-Tier Stale Policy:**
- Standard timeline: Issues/PRs still follow 365→30 day cycle
- Accelerated timeline: Issues with needs-information label now get 30→7 day cycle
- Separate jobs handle each policy independently
- Detailed messages explaining why items are marked stale and how to keep them open
- Exempt labels: `no-stale`, `needs-information` (for standard policy)
- Only `no-stale` exempt for PRs (`needs-info` doesn't apply)
=> Add stale issue management workflow
