redis/ioredis

- README.md
> Add missing http:// prefix to README

- README.md
- lib/cluster.js
- test/functional/cluster.js
Should fix #110.
There're some places should be refactored though.
> Auto-resubscribe channels in cluster mode.

- benchmarks/single_node.js
增加pub/sub的压力测试
|对象|项目|数据|
|-----|:---:|:---:|
|ioredis|publish|45k+ opt/s(单进程publish)|
|node_redis|publish|43k+ opt/s(单进程publish)|
|ioredis|subscribe|200k+ opt/s峰值(多进程publish)|
|ioredis|subscribe|5k+ opt/s谷值(多进程publish)|
|node_redis|subscribe|100k+ opt/s(多进程publish)|
与本机测试不同，由于是单进程、及subscribe在EventEmitter中，没想到基于matcha好的测试方法。
```
==========================
ioredis: 1.7.2
node_redis: 0.12.1
CPU: 4
OS: darwin x64
==========================
publish
42,227 op/s » ioredis
39,452 op/s » node_redis
|
subscribe
32,625 op/s » ioredis
34,855 op/s » node_redis
/
\
Suites:  2
Benches: 4
Elapsed: 29,195.12 ms
```
改善subscribe的测试方法，最好是多进程协作形成测试结果。
> bench pub/sub

- lib/commander.js
This fixes some incorrectly indented lines.
> Fix indentation in commander.js

- lib/pipeline.js
- test/functional/pipeline.js
> Fix empty pipeline not resolving as empty array

- lib/cluster.js
> Fix errors when sending command to a failed cluster. #56

- lib/cluster.js
- lib/pipeline.js
- lib/redis.js
> `_.extend` to `_.assign`

- Changelog.md
- README.md
- lib/connectors/connector.js
> Add support for TLS

- README.md
> Added example in docs to create keys with expires

- lib/connectors/sentinel_connector.js
Flags s_down and o_down are not being taken in account when connecting.
> Discard slave if flagged with s_down or o_down

- README.md
- lib/redis/event_handler.js
- test/functional/auth.js
> Emit auth error for wrong password

- lib/redis.js
[See API page](https://nodejs.org/api/tls.html#tls_class_tls_tlssocket_1)
TLS stream upon connection emits "secureConnect" event.
Tested against *stunnel*
> Fix tls connect event is "secureConnect"

- benchmarks/single_node.js
- node version
- current commit tree-ish
> add: more useful info for benchmarks

- lib/cluster.js
> add queue support for cluster failover & cluster down handling

- lib/scan_stream.js
Close and let the buffer drain.
> Made scan streams closeable

- lib/redis/event_handler.js
- test/functional/auth.js
> fix(auth): emit authError when the server requiring a password

- API.md
- lib/redis.js
- lib/redis/parser.js
- test/functional/string_numbers.js
> feat: add stringNumbers option to return numbers as JavaScript strings

- lib/redis.js
- test/functional/connection.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/luin/ioredis/290)
> fix: fix wrong host not causing error

- test/functional/connection.js
Fix typos in tests messages in order to look better :)
> Fix typo in connection test file

- lib/connectors/sentinel_connector.js
Based on http://redis.io/topics/sentinel-clients#sentinels-list-automatic-refresh. Closes #304.
> Update sentinels after getting master.

- API.md
- lib/redis.js
- lib/redis/parser.js
Minor change, just fixing the spelling of "recommended".
> Fixing spelling of "recommended"

- lib/utils/index.js
> Rewrite utils.convertObjectToArray

- lib/cluster/index.js
> Add option to control timeout on cluster slots refresh

- .travis.yml
- lib/reply_error.js
Previously in Node.js v8:
After this pull request:
> Node 8 support

- README.md
When dealing with binary hash keys, the default reply transformer for `hgetall` is performing a unwanted conversion of hash keys to string.
I added a new reply transformer example to the README which shows how the reply format can be changed to array of arrays, it might be useful for other people.
> docs(README): add example for hgetall AoA reply transformer

- lib/index.js
I needed to add some logic to Pipeline.
The pipeline prototype wasn't exposed.
I wanted to extends the prototype and because of this I made this pull request.
> Export class Pipeline to be able to extend it 

- README.md
I've used a Set to handle the deduplication in the example, but I can switch it to a plain old object as I wrote in the comment if that feels less out of place.
> Mention duplicate keys in scan stream example

- package-lock.json
- package.json
This should open up access to Redis 5.0 streams as requested by #621, among others.
> deps: upgrade redis-commands package

- lib/connectors/SentinelConnector/index.ts
Fixes https://github.com/luin/ioredis/issues/740
> Allow TLS when using Sentinel

- lib/cluster/ClusterSubscriber.ts
- test/functional/cluster/tls.js
Fix for issue: https://github.com/luin/ioredis/issues/791
> fix: subscriber initialization when using Cluster + TLS

- lib/connectors/SentinelConnector/index.ts
- lib/redis.js
- test/functional/sentinel.js
Pull request implementing new option for suggested fix in Issue #798 - SentinelIterator iterator grows indefinitely with unwanted ips
> feat: add updateSentinels option to control new sentinel values being added

- README.md
- lib/connectors/SentinelConnector/index.ts
- test/functional/sentinel.js
#816 
I apologize for any inconvenience due to typo and insufficient testing.
I wrote a test referring to the content of the comment.
> support Sentinel instances with authentication.

- README.md
- examples/basic_operations.js
Updated the documentation with reference to the 'del' operation.
> issue #854 Update example with 'del' operation

- lib/cluster/index.ts
> chore: prune old options assignment

- lib/cluster/ClusterSubscriber.ts
- lib/cluster/ConnectionPool.ts
- lib/cluster/DelayQueue.ts
- lib/cluster/index.ts
- lib/commander.ts
- lib/connectors/SentinelConnector/index.ts
- lib/index.ts
- lib/pipeline.ts
- lib/redis/RedisOptions.ts
- lib/redis/index.ts
- test/unit/commander.js
- tsconfig.json
Minor tweaks to make the last two files written in TS
> Make last two files typescript

- .eslintrc.yml
- benchmarks/single_node.ts
- lib/DataHandler.ts
- lib/SubscriptionSet.ts
- lib/cluster/ClusterOptions.ts
- lib/cluster/ClusterSubscriber.ts
- lib/cluster/index.ts
- lib/cluster/util.ts
- lib/command.ts
- lib/commander.ts
- lib/connectors/SentinelConnector/SentinelIterator.ts
- lib/connectors/SentinelConnector/index.ts
- package.json
- test/functional/auth.ts
- test/functional/cluster/transaction.ts
- test/functional/fatal_error.ts
- test/functional/scan_stream.ts
- test/functional/sentinel.ts
- test/unit/debug.ts
- test/unit/utils.ts
Noticed that `eslint .` ignores ts files. Then I went through and fixed some warnings and added rule overrides for things that look part of your styling.
> Fix eslint args and fixed new lint errors

- lib/connectors/StandaloneConnector.ts
- lib/redis/event_handler.ts
- lib/redis/index.ts
- test/functional/connection.ts
- test/unit/connectors/connector.ts
Close #928.
Tests are needed for this pull request before merging.
> fix: handle connecting immediately after "end" event

- lib/cluster/ConnectionPool.ts
- test/unit/clusters/ConnectionPool.ts
- test/unit/clusters/index.ts
> Make NAT works with enableReadyCheck 

- lib/connectors/SentinelConnector/SentinelIterator.ts
- test/functional/sentinel.ts
- test/unit/connectors/SentinelConnector/SentinelIterator.ts
> fix: keep sentinels of options immutable

- README.md
show monitor.disconnect() async function example
> show monitor.disconnect() async function example

- README.md
- examples/redis_streams.js
Added an example for how to use the commands through ioredis interface:
- XADD
- XREAD
- XLEN
https://redis.io/topics/streams-intro
> Add Examples for using Redis Streams Commands 

- README.md
Closes #1250. Thank @joaopaulobdac for the suggestion!
> docs(README): convert benchmarks tables to markdown

- package-lock.json
- package.json
Closes #1281
This change will add commands introduced in recent Redis unstable versions.
> Upgrade command list to Redis 6.2

- lib/connectors/AbstractConnector.ts
- lib/connectors/SentinelConnector/index.ts
- lib/connectors/StandaloneConnector.ts
- lib/redis/index.ts
- test/functional/connection.ts
- test/unit/connectors/connector.ts
This should fix the connection issues described in #1296.
Closes #1236
Closes #1209
Closes #1289
Closes #1296
> Handle instant stream error

- README.md
> docs(README): improve the documentation for pubsub

- README.md
> docs(README): document the "wait" event

- README.md
Hey ioredis folks,
First of all, thanks for putting this library together!
I've been through the docs and found those tiny typos. Opening this little PR here to fix them.
Thanks!
> Fix docs typos

- lib/autoPipelining.ts
- lib/command.ts
- lib/redis/RedisOptions.ts
- lib/redis/index.ts
- lib/script.ts
- lib/transaction.ts
- lib/utils/index.ts
There's still hundreds of errors with noImplicitAny
> Add a few typescript types

- .dockerignore
- .github/workflows/main.yml
- .travis.yml
- README.md
- lib/utils/index.ts
- test/docker/Dockerfile
- test/docker/main.sh
- test/docker/worker.sh
- test/functional/cluster/pub_sub.ts
- test/functional/connection.ts
- test/functional/ready_check.ts
- test/functional/sentinel.ts
- test/functional/transformer.ts
- test/helpers/global.ts
- test/helpers/util.ts
~~Note that enabling github workflows requires that a github workflows file be set up on master first for PRs by non-owners of a repo.~~ (never mind, seemed to work)
(for first-time contributors, github workflows also requires that maintainers manually approve the run, to avoid bot activity wasting CI machine resources)
This adds commits on top of https://github.com/luin/ioredis/pull/1468
> Set up github actions for CI. Support testing with older redis server versions. Start testing with node 16

- README.md
- lib/command.ts
- lib/script.ts
- lib/utils/Commander.ts
- test/functional/transformer.ts
- test/unit/utils.ts
- 👷 Remove typeof Map checks as we've dropped older node versions
- 🚀 Reduce amount of command args iterations
> Reduce amount of command args iterations

- lib/cluster/ClusterOptions.ts
- lib/cluster/index.ts
- test-cluster/basic.ts
- test/unit/clusters/index.ts
> Support passing keyPrefix via redisOptions

- lib/index.ts
> feat: add named export

- bin/returnTypes.js
- lib/utils/RedisCommander.ts
- test/typing/commands.test-d.ts
> fix: srandmember with count argument should return array of strings or array of unknown

- README.md
> docs: add notice for TLS profile settings

- .github/workflows/test.yml
> Add node 18 to CI

- lib/redis/event_handler.ts
> Fix commands not resend on reconnect in edge cases

- lib/autoPipelining.ts
- test/functional/autopipelining.ts
> fix: Fix db parameter not working with auto pipelining

- README.md
This works per <https://stackoverflow.com/a/66810848>.
> docs: added note regarding passing empty tls object

- lib/Redis.ts
> fix: remove console.log

- README.md
- lib/ScanStream.ts
- lib/types.ts
- test/functional/scan_stream.ts
Adding the option NOVALUES to the hscanStream
In order to close the #1942
> feat(HscanStream): adding NOVALUES option

- README.md
Adresses https://github.com/redis/ioredis/issues/1871
> Fix xread example for TypeScript

- lib/utils/RedisCommander.ts
- test/functional/commands/xtrim.ts
- Regenerate RedisCommander.ts with complete XTRIM signatures
- Add test suite for XTRIM command
Addresses #2009
> feat: add more xtrim method overloads and tests
